### PR TITLE
feat: improve forwarding-events with `preserveBehavior`

### PR DESCRIPTION
**Pull request by franpeza**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

This PR adds the ability to preserve the behavior of forwarded functions. This comes in candy for some scenarios, for example, some third parties integrations that monitor the global `dataLayer` array in order to work. When GA is handled by partytown the array will be empty, this new functionality allows to keep the events there.

Even if the motivation for this is GA and the dataLayer array, this would work for any other forwarded method, as it makes the trick including a call to the original method in the patched version (in fact, in the tests added there is a case where the forwarded method is `unshift` instead of `push`).

If you want to enable this new setting, you would do it like this:
`forward: ['simpleProperty', ['dataLayer.push', { preserveBehavior: true }]],`
I also contemplated the possibility of doing so:
`forward: ['simpleProperty', { property: 'dataLayer.push', preserveBehavior: true }],`
but I prefer the first way. Anyway I'm open to implement any other way of doing it.

# Use cases and why

- 1. GA integration, as described above.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (not yet)
- [x] Added new tests to cover the fix / functionality

If you think this PR is worth, I could add the documentation of the new setting.
Waiting for your feedback, thank you!

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks @franpeza I think this is a nice improvement. my only concern is to have to different way of doing the same thing.
Let's just keep the first one.
`forward: ['simpleProperty', ['dataLayer.push', { preserveBehavior: true }]]`
Are there any open issues for this?

**Comment by franpeza** [comment]
thanks @gioboa, what I was trying to expose was some possible ways to allow to inform the property, but the one I implemented is precisely the one you mentioned (and my favourite one BTW) So that would be the only way of enabling this new setting.

Don't know if there's any open issue regarding this topic, not on my side at least.

I will try to make some time today or tomorrow to document the property with this shape:

`forward: ['simpleProperty', ['dataLayer.push', { preserveBehavior: true }]]`

**Comment by gioboa** [comment]
I'll fix it

**Comment by franpeza** [comment]
thanks @gioboa

**Comment by gioboa** [comment]
Tests are so unstable 😢  I can't figure out the why

**Comment by franpeza** [comment]
> Tests are so unstable 😢 I can't figure out the why

The more unstable seems to be the webkit one, yep

I just added some documentation about the new setting, please take a look if you can :)

**Comment by franpeza** [comment]
Thanks for merging it!!

**Pull request merged**
