### PR TITLE
fix: service worker communicates with the latest client only

### PR DESCRIPTION
**Pull request by vladetsky**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests

# Description

For some reason service worker is set to send messages to the latest client only. This leads to `error finding instance`, when user opens several tabs in the browser and switches not to the latest tab. More description [here](https://github.com/BuilderIO/partytown/issues/202).

# Use cases and why

Open several tabs in the browser with the same site. Partytown should run with service worker, not Atomics.
Switch to the first tab. Now anytime web worker tries to send anything to the main thread, you'll get `error finding instance`. The problem is in below code, where service worker is set to send messages to the latest tab only.
```
const sendMessageToSandboxFromServiceWorker = (accessReq: MainAccessRequest) =>
  new Promise<MainAccessResponse>(async (resolve) => {
    const clients = await (self as any as ServiceWorkerGlobalScope).clients.matchAll();
    const client = [...clients].sort((a, b) => {
      if (a.url > b.url) return -1;
      if (a.url < b.url) return 1;
      return 0;
    })[0];
```

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by techfg** [comment]
@vladetsky - Awesome to see this get fixed, thank you!  I've confirmed that all of the tests added in #493 which adds tests for #492 pass with your fix applied.  Once this PR is merged, I'll adjust #493 so it can be merged to add some additional test coverage for your fix.

**Comment by vladetsky** [comment]
> @vladetsky - Awesome to see this get fixed, thank you! I've confirmed that all of the tests added in #493 which adds tests for #492 pass with your fix applied. Once this PR is merged, I'll adjust #493 so it can be merged which will add some additional test coverage for your fix.

Thanks for testing this fix @techfg !

**Comment by gioboa** [comment]
Thanks @vladetsky @techfg  for your help

**Review by gioboa — APPROVED** [review]
Thanks @vladetsky for this great improvement :clap:

**Comment by tibineagu** [comment]
@vladetsky unfortunately I think this might still be happening.

Please check out [`tibineagu/partytown-instance-error`](https://github.com/tibineagu/partytown-instance-error) - it's using `0.10.1` which should in theory include your fix.

**Comment by vladetsky** [comment]
> @vladetsky unfortunately I think this might still be happening.
> 
> Please check out [`tibineagu/partytown-instance-error`](https://github.com/tibineagu/partytown-instance-error) - it's [using](https://github.com/tibineagu/partytown-instance-error/blob/d6005fcf18aaae11a5ed48be8fa24de9ffe9fbac/pnpm-lock.yaml#L8-L10) `0.10.1` which [should include](https://github.com/BuilderIO/partytown/releases/tag/v0.10.1) your fix.
> 
> I tried to keep the repro as simple as possible. The proxied function simply [gets and sets from localStorage](https://github.com/tibineagu/partytown-instance-error/blob/d6005fcf18aaae11a5ed48be8fa24de9ffe9fbac/index.html#L25-L30).
> 
> As soon as another tab is open, the errors start popping up again.

@tibineagu You have an outdated inline script [here](https://github.com/tibineagu/partytown-instance-error/blob/d6005fcf18aaae11a5ed48be8fa24de9ffe9fbac/index.html#L21-L22). Please update it to `0.10.1` and check.

**Comment by tibineagu** [comment]
@vladetsky oh my god you're right - i must have copied that from the wrong place.

Works as expected with the snippet code from `lib/partytown.js`

Sorry about the mix-up! 😬

**Comment by vladetsky** [comment]
> @vladetsky oh my god you're right - i must have copied that from the wrong place.
> 
> Works as expected with the snippet code from `lib/partytown.js`
> 
> Sorry about the mix-up! 😬

No worries @tibineagu , thanks for testing!

**Pull request merged**
