### PR TITLE
chore: cleanup and add tests

### PR DESCRIPTION
**Pull request by molszanski**
# What is it?

- [x] Docs / tests

# Description

This is follow up PR that cleans up code and adds tests
https://github.com/BuilderIO/partytown/pull/453/files

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by mhevery** [comment]
Do you think you could have a look at the broken tests... I would love to get this landed.

**Comment by molszanski** [comment]
https://github.com/BuilderIO/partytown/pull/478
Seems like the master is broken :/

**Comment by molszanski** [comment]
@gioboa can you rerun tests on this branch?

**Comment by gioboa** [comment]
Tests are green 😊 💚

**Review by gioboa — APPROVED** [review]
Thanks for your help.

**Pull request merged**
