### PR TITLE
test: multiple page tests for #492

### PR DESCRIPTION
**Pull request by techfg**
# What is it?

- [ ] Feature / enhancement
- [X] Bug
- [X] Docs / tests

# Description

Tests to reproduce #492 

# Use cases and why

When multiple tabs/pages are open, the error `$instanceId$ not found` is encountered when attempting to access main thread. See #492 for details.

# Checklist:

- [X] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks @techfg I'll resolve the conflicts.

**Comment by techfg** [comment]
> Thanks @techfg I'll resolve the conflicts.

Thanks @gioboa!  Unfortunately, the merge resulted in two tests no longer failing so I've reverted back to the order of operations that existed from prior commit.  In short, the bug that exists is whenever two (or more) tabs/pages are open, if you go back to the first page (and sometimes even on the 2nd), you'll encounter the error so it's important for both pages to be loaded and then interact with them.

This does seem to be a fairly significant issue as any time more than one tab/page is open on a site that uses PT, unless Atomics are used, the problem will arise.  Any insight on when #492 could be looked at?

**Comment by gioboa** [comment]
May I suggest you to checking it out pls?

**Comment by techfg** [comment]
> May I suggest you to checking it out pls?

Sorry @gioboa, is question intended for me? If so, sorry, I don't understand what you'd like me to check out?

**Comment by gioboa** [comment]
> Any insight on when #492 could be looked at?

I was referring to this.

**Comment by techfg** [comment]
> > Any insight on when #492 could be looked at?
> 
> I was referring to this.
> 
> 

@gioboa - gotcha, thanks for clarifying. I was the one that created #492. I believe the root issue is in the way PT tracks instances but doesn't recognize multiple windows when posting messages back and forth. I'm not familiar with the core internals so was hopeful someone from PT team who's more familiar could review and resolve. Steps to easily reproduce issue are in #492.  Thanks!

**Pull request merged**
