### PR TITLE
docs: fix typo in facebook-pixel page

### PR DESCRIPTION
**Pull request by abdelsalamshahlol**
# What is it?

- [✖️] Feature / enhancement
- [✖️] Bug
- [✅] Docs / tests

# Description
Updated code example snippet and corrected an issue in code syntax.

# Use cases and why
N/A

# Checklist:

- [ N/A] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md)
- [✅] I have performed a self-review of my own code
- [✅] I have made corresponding changes to the documentation
- [N/A] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
Thanks @abdelsalamshahlol you rock 🚀

**Comment by gioboa** [comment]
Just for curiosity, what's your stack @abdelsalamshahlol ?

**Comment by abdelsalamshahlol** [comment]
@gioboa Currently I'm focusing on Frontend and I use Angular, React, and Vue. But I also use Laravel and Express with MySQL for my side projects.

**Comment by abdelsalamshahlol** [comment]
No, it's an Angular app @gioboa

**Comment by gioboa** [comment]
is [the Angular guide](https://partytown.builder.io/angular) good enough for you? Can we improve something?

**Comment by abdelsalamshahlol** [comment]
@gioboa it was good for me but I think it's missing adding partytown script to scripts in `package.json`

**Comment by gioboa** [comment]
May I suggest you to drop a PR for that?

**Pull request merged**
