### PR TITLE
Added a test case to reproduce bug

### PR DESCRIPTION
**Pull request by yeslad**
Script tag is added to the DOM with `type=text/partytown`, the `src` is never fetched.

### CODE REVIEW

**Comment by adamdbradley** [comment]
Sorry could you describe the issue a big more? I'm not fully understanding what this test is doing. Thanks

**Comment by yeslad** [comment]
GTM drops a script tag, but instead of loading this script, Partytown is appending a script tag with `type="text/partytown"` to the DOM.

**Comment by gioboa** [comment]
Hi @yeslad, is it still a valid PR?

**Comment by yeslad** [comment]
Not really, no.

**Pull request closed without merging**
