### PR TITLE
fix(firefox): remove setTimeout from onLocationChange

### PR DESCRIPTION
**Pull request by emish89**
# What is it?

-  Bug

# Description

I removed a setTimeout that was giving error on firefox after page change. There are more open issues for this.

# Use cases and why

I expect that now firefox works

### CODE REVIEW

**Review by mhevery — COMMENTED** [review]
This looks reasonable, I will try to dig into why `setTimeout` is there. In the meantime could we have a test https://github.com/BuilderIO/partytown/tree/main/tests/platform which shows that the issue has been fixed?

**Comment by emish89** [comment]
> This looks reasonable, I will try to dig into why `setTimeout` is there. In the meantime could we have a test https://github.com/BuilderIO/partytown/tree/main/tests/platform which shows that the issue has been fixed?

can you help me create a proper test?

I tried adding "firefox" to playwright but almost all the tests are failing. So I'm not sure on how to proceed and I prefer waiting for some help.

The issue happens only in firefox, at first page change. 

The open bugs are at least these:
https://github.com/BuilderIO/partytown/issues/505
https://github.com/BuilderIO/partytown/issues/486
https://github.com/BuilderIO/partytown/issues/457
https://github.com/withastro/astro/issues/8862

**Comment by gioboa** [comment]
HI @emish89
I added the firefox scripts and your change it's working fine.

**Comment by emish89** [comment]
great, so you think can be merged?

**Comment by gioboa** [comment]
there is not tests for `onLocationChange` method.
Can you add them pls?

**Comment by gioboa** [comment]
I investigated and `"astro": "^4.0.6"` solve this issue without change anything in PartyTown.
Can you check @emish89 pls?

**Comment by emish89** [comment]
> I investigated and `"astro": "^4.0.6"` solves this issue without change anything in PartyTown. Can you check @emish89 pls?

I was involved in the astro fix. If you see the code: https://github.com/withastro/astro/pull/9419/files

you can see that the history APIs has been replaced. With these changes, from your point of view, partytown library is still working as expected? 

It was intended as a temporary fix until partytown solves the problems with firefox from what I've understood.

**Review by mhevery — APPROVED** [review]
LGTM, but there is a failure.

**Comment by gioboa** [comment]
@emish89 the failing test is a flaky one. Now we have a green line.

**Pull request merged**
